language: csharp
sudo: required  
dist: xenial 
mono:
  mdk: latest
  android: 7.0.2-42
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    - extra-android-support
    licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
os:
  - osx
solution: VideoPlayerProima.sln
env:
  global:
    - ResolveNuGetPackageAssets=true
    - EnableNuGetPackageRestore=true
    - ANDROID_COMPONENTS=build-tools-25.0.1,android-26,extra-android-support,extra-google-google_play_services,extra-google-m2repository,extra-android-m2repository
    - ANDROID_LICENSES=android-sdk-license-c81a61d9
    - MONO_VERSION=4.6.2
    - MONO_ANDROID_VERSION=7.0.2-42
before_install:
  - yes | sdkmanager "platforms;android-27"
install:
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$ANDROID_COMPONENTS --accept=$ANDROID_LICENSES
  - source ~/.android-sdk-installer/env
  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-universal/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.universal.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.universal.pkg" -target /
  - wget "https://dl.xamarin.com/MonoforAndroid/Mac/xamarin.android-${MONO_ANDROID_VERSION}.pkg"
  - sudo installer -pkg "xamarin.android-${MONO_ANDROID_VERSION}.pkg" -target /
  - /Library/Frameworks/Mono.framework/Commands/nuget restore VideoPlayerProima.sln
script:
  - /Library/Frameworks/Mono.framework/Commands/xbuild /t:SignAndroidPackage /p:Configuration=Release VideoPlayerProima.Android/VideoPlayerProima.Android.csproj

